### ISSUE TITLE
Few little defects about black fonts on Projects tab in Qt Creator 4.3.1

### ISSUE THREAD

**Issue by ivakyb** [Kojoley/qss-dracula#1]
![image](https://user-images.githubusercontent.com/7225779/31227500-ba4147e2-a9e2-11e7-8af8-79e57533cc15.png)

**Comment by ivakyb** [comment]
There is a dark theme embedded in this release. May be this one with few improvements. Thanks for your work!

**Comment by Kojoley** [comment]
Thanks for you report.
This type of bugs cannot be fixed in QSS because the color values for painting device are overridden [like this](https://github.com/qt-creator/qt-creator/blob/89057b552b0b9bbe24d4e3552e12ae94aa713fa8/src/plugins/projectexplorer/projectwindow.cpp#L648-L649).

I really should have rewritten the style into a theme since QtCreator supports native theming already for a quite long period of time.
